project:
  type: website
  output-dir: _site

website:
  title: "Roopa's Visual Cloud"

  navbar:
    logo: images/snoopy-main.png
    title: "Roopa's Visual Cloud"
    left:
    - text: "{{< fa house-chimney >}}"
      href: index.qmd
    - text: "{{< fa cloud >}}"
      href: about.qmd
    - text: "{{< fa seedling >}}"
      href: https://github.com/rooparrk
    
    right:
    - text: Hands-on
      href: Hands-on_Ex/
    - text: Take-Home
      href: Take-Home_Ex/
    - text: In-Class
      href: In-Class_Ex/

  page-footer:
    center: "Roopa ☁️ | Visual Analytics"

format:
  html:
    theme:
      - cosmo
      - theme.scss
    css: styles.css
    toc: false
    page-layout: full

editor: visual
