project:
  type: website
  output-dir: _site

website:
  title: "Roopa's Visual Cloud"

  navbar:
    logo: images/snoopy-main.png
    title: "Roopa's Visual Cloud"
    right:
      - text: Home
        href: index.qmd
      - text: Hands-on
        href: Hands-on_Ex/
      - text: Take-Home
        href: Take-Home_Ex/
      - text: In-Class
        href: In-Class_Ex/
      - text: About
        href: about.qmd

  page-footer:
    center: "Roopa ☁️ | Visual Analytics"

format:
  html:
    theme:
      - cosmo
      - theme.scss
    css: styles.css
    toc: false
    page-layout: full

editor: visual
