project:
  type: website
  output-dir: _site

website:
  title: "Roopa's Visual Cloud"

  navbar:
    logo: images/snoopy-main.png
    title: "Roopa's Visual Cloud"
    left:
    - text: "{{< fa hand-sparkles >}} Hands-on"
      menu:
        - text: "Exercise 1: ggplot2"
          href: Hands-on_ex/Hands-on_ex01/Hands-on_ex01.html
    - text: "{{< fa magnifying-glass-chart >}} Take-Home"
      href: Take-Home_Ex/
    - text: "{{< fa pen-to-square >}} In-Class"
      href: In-Class_Ex/

    
    right:
    - text: "{{< fa house-chimney >}}"
      href: index.qmd
    - text: "{{< fa cloud >}}"
      href: about.qmd
    - text: "{{< fa seedling >}}"
      href: https://github.com/rooparrk
    

  page-footer:
    center: "Roopa ☁️ | Visual Analytics"

format:
  html:
    theme:
      - cosmo
      - theme.scss
    css: styles.css
    toc: false
    page-layout: full

editor: visual
